# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'pcs-test-pool'

steps:
- script: |
    echo Initialize
    Terraform --version
  displayName: 'Sample Terraform execution'

