# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'pcs-test-pool'

variables:
  library: samples

steps:
- pwsh: |
    echo --- Initialize ---
    terraform --version
    pwd
    cd logicapps
    terraform init -backend-config "storage_account_name=$(tfStorageAccount)" `
    -backend-config "container_name=$(tfStateContainerName)" `
    -backend-config "access_key=$(tfAccountKey)" `
    -backend-config "key=$(MyEnvironmentName).sample.tfstate" `
    -input=false
  displayName: 'Terraform init'
  workingDirectory: ./logicapps

- script: |
    echo --- Plan ---
    terraform plan -out plan.out -var "subscription_id=$(subscription_id)" -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var-file "..\config\logicapp.tfvars"
  displayName: 'Terraform plan'

- script: |
    # echo --- Apply ---
    # terraform apply plan.out
  displayName: 'Terraform apply'

