# Verify terraform script

trigger:
- dev/*

pool:
  name: 'Terraform-windows-agents'

variables:
- name: target-dir
  value: "./logicapps"
- group: samples

steps:
- powershell: |
    pwd
    echo --- Terraform check ---
    terraform --version
    terraform init
    terraform validate -no-color
  displayName: 'Validate Terraform'
  workingDirectory: $(target-dir)

- powershell: |
    $result = Select-String -Path *.tf -Pattern "^resource"
    if ($result) {
        $result
        exit 1
    }
    else {
        exit 0
    }
  displayName: 'Check terraform'
  workingDirectory: $(target-dir)


