# Terraform plan and apply

trigger:
- master

pool:
  name: 'Terraform-windows-agents'

variables:
- name: target-dir
  value: "./logicapps"
- group: samples
- group: tags


jobs:
- job: init_and_plan
  steps:
  - powershell: .\build\create-tfvars.ps1
    displayName: 'Build tfvars'
    workingDirectory: $(target-dir)
  
  - task: PowerShell@2
    displayName: 'terraform init'
    inputs:
      targetType: 'inline'
      script: |
        terraform init `
          -backend-config="resource_group_name=$(resource_group_name)" `
          -backend-config="storage_account_name=$(tfStorageAccount)" `
          -backend-config="container_name=$(tfStateContainerName)" `
          -backend-config="access_key=$(tfAccountKey)" `
          -backend-config="key=$(MyEnvironmentName).sample.tfstate" `
          -input=false  3>warn.txt 2>error.txt >output.txt
      workingDirectory: '$(target-dir)'

  # - task: PowerShell@2
  #   displayName: 'terraform plan'
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       $cmd = "terraform plan -out plan.out -input=false "
  #       $cmd += "-var-file main.tfvars "
  #       $cmd += "-var `"subscription_id=$(subscription_id)`" "
  #       $cmd += "-var `"client_id=$(client_id)`" " 
  #       $cmd += "-var `"client_secret=$(client_secret)`" "
  #       $cmd += "-var `"tenant_id=$(tenant_id)`" "
  #       iex $cmd 
  #     workingDirectory: '$(target-dir)'

  - task: AzureCLI@2
    displayName: plan
    inputs:
      azureSubscription: 'mti-policy-01-srvc'
      scriptType: 'batch'
      scriptLocation: 'inlineScript'
      inlineScript: |
        terraform plan -out plan.out  ^
          -var-file "main.tfvars" ^
          -var "subscription_id=${subscription_id}" ^
          -var "client_id=$servicePrincipalId" ^
          -var "client_secret=$servicePrincipalKey" ^
          -var "tenant_id=$tenantId" ^
          -input=false  3>warn.txt 2>error.txt >output.txt
        "---- warnings --- "
        type warn.txt
        "--- errors ---"
        type error.txt
        "--- output ---"
        type output.txt
      addSpnToEnvironment: true
      workingDirectory: '$(target-dir)'


- job: confirm_plan
  dependsOn: init_and_plan
  displayName: Review and confirm plan  
  pool: server    
  timeoutInMinutes: 2880 # times out in 2 days
  steps:   
  - task: ManualValidation@0
    timeoutInMinutes: 1440 # task times out in 1 day
    inputs:
      notifyUsers: |
        pspokas@micron.com
      instructions: 'Please validate the build configuration and resume'
      onTimeout: 'resume'

- job: apply
  dependsOn: confirm_plan
  steps:
  - script: |
      echo --- Apply ---
      terraform apply plan.out
    displayName: 'Terraform apply'
    workingDirectory: $(target-dir)

